export default users = [
    {
        id: 1,
        name: 'John Doe',
        email: 'johndoe@example.com',
        phone: '123-456-7890',
        address: '123 Main St, Anytown, USA',
        avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    {
        id: 2,
        name: 'Jane Smith',
        email: 'janesmith@example.com',
        phone: '987-654-3210',
        address: '456 Elm St, Anytown, USA',
        avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    },
    {
        id: 3,
        name: 'Bob Johnson',
        email: 'bobjohnson@example.com',
        phone: '555-123-4567',
        address: '789 Oak St, Anytown, USA',
        avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
    },
    {
        id: 4,
        name: 'Alice Brown',
        email: 'alicebrown@example.com',
        phone: '111-222-3333',
        address: '321 Pine St, Anytown, USA',
        avatar: 'https://randomuser.me/api/portraits/women/4.jpg',
    },
    {
        id: 5,
        name: 'Charlie Davis',
        email: 'charliedavis@example.com',
        phone: '444-555-6666',
        address: '654 Maple St, Anytown, USA',
        avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
    },
    {
        id: 6,
        name: 'Eva Wilson',
        email: 'evawilson@example.com',
        phone: '777-888-9999',
        address: '987 Cedar St, Anytown, USA',
        avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
    },
    {
        id: 7,
        name: 'Frank Lee',
        email: 'franklee@example.com',
        phone: '222-333-4444',
        address: '321 Birch St, Anytown, USA',
        avatar: 'https://randomuser.me/api/portraits/men/7.jpg',
    },
    {
        id: 8,
        name: 'Grace Turner',
        email: 'graceturner@example.com',
        phone: '555-666-7777',
        address: '654 Oak St, Anytown, USA',
        avatar: 'https://randomuser.me/api/portraits/women/8.jpg',
    },
    {
        id: 9,
        name: 'Henry Adams',
        email: 'henryadams@example.com',
        phone: '888-999-0000',
        address: '987 Oak St, Anytown, USA',
        avatar: 'https://randomuser.me/api/portraits/men/9.jpg',
    },
    {
        id: 10,
        name: 'Ivy Green',
        email: 'ivygreen@example.com',
        phone: '111-222-3333',
        address: '321 Pine St, Anytown, USA',
        avatar: 'https://randomuser.me/api/portraits/women/10.jpg',
    },
];